import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { AppContainer, Navbar } from "@/components";
import { MouseProvider } from "@/context/MouseMoveContext";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MouseProvider>
        <body className={jakarta.className}>
          <Navbar />
          <AppContainer> {children}</AppContainer> 
        </body>
      </MouseProvider>
    </html>
  );
}
