import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { AppContainer, Navbar } from "@/components";
import { MouseProvider } from "@/context/MouseMoveContext";
import { Suspense } from "react";
import Loading from "./loading";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MouseProvider>
        <body>
          <AppContainer><Suspense fallback={<Loading/>}>{children}</Suspense></AppContainer>
        </body>
      </MouseProvider>
    </html>
  );
}
